config/routes.rb
SampleApp::Application.routes.draw do
  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  match '/contact', to: 'static_pages#contact'

  match '/patient', to: 'static_pages#patient'

  match '/clinician', to: 'statis_pages#clinician'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def patient
  end

  def clinician
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy;Welch & Co. All rights reserved.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Doxy.me", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
           <li><%= link_to "Sign in", "#" %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doxy.me - The simple, free, secure way for your doc to see you</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>

app/views/static_pages/clinician.html.erb
<div class="center hero-unit">
	<h1>Doxy.me</h1>

	<h2>The simple, free, secure way for your doc to see you.</h2>

<div class="ads">
	
</div>
<div class="tokbox">
	<!-- Tokbox code goes here -->
</div>

<div class="right_bar">
	<div class="info"></div>
	<div class="participants"></div>
	<div class="chat"></div>
</div>

  <%= link_to "Sign up for updates!", '#', class: "btn btn-large btn-primary" %>

</div>

app/views/static_pages/contact.html.erb
<% provide( :title, 'Contact Us' ) %>
<h1>Contact Us</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Doxy.me</h1>

	<h2>The simple, free, secure way for your doc to see you.</h2>



<div class="row">
	<div class="span2">
		<%= image_tag "lipitor_ad.png" %>
		<%= image_tag "ativan_ad.png" %>
		<%= image_tag "bc_ad.png", :class => "style_image" %>
	</div>
	
	<div class="span6">
		<!-- Tokbox code goes here -->
		<iframe class="f2f" src="https://apprtc.appspot.com/?r=03029823">
	    <p>AppRTC Widget</p>
		</iframe>
	</div>
	
	<div class="span1"><iframe class="c2c" src="http://cdn.peerjs.com/demo/chat-old.html" frameborder="0"></iframe></div>
</div>

  <%= link_to "Sign up for updates!", '#', class: "btn btn-large btn-primary" %>

</div>

app/views/static_pages/patient.html.erb
<div class="center hero-unit">
	<h1>Doxy.me</h1>

	<h2>The simple, free, secure way for your doc to see you.</h2>
	
<div class="pat_tokbox">
	<!-- Tokbox code goes here -->
	<iframe class="f2f" src="https://apprtc.appspot.com/?r=03029823">
    <p>AppRTC Widget</p>
</iframe>
</div>

<div class="right_bar">
	<div class="meeting_info">
		Physician: <br />Dr. Chestnut<br />
		
	</div>
	<div class="pat_chat">Chat</div>
</div>

</div>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>